import { au, ly } from './format';

export type Category =
  | 'moon'
  | 'planet'
  | 'star'
  | 'nebula'
  | 'cluster'
  | 'galaxy'
  | 'blackhole'
  | 'exoplanet'
  | 'probe'
  | 'structure'
  | 'edge';

export interface CategoryMeta {
  id: Category;
  label: string;
  blurb: string;
}

export const CATEGORIES: CategoryMeta[] = [
  { id: 'moon', label: 'Moons', blurb: 'Worlds that orbit worlds' },
  { id: 'planet', label: 'Planets & worlds', blurb: 'The neighbourhood' },
  { id: 'star', label: 'Stars', blurb: 'Furnaces with names' },
  { id: 'nebula', label: 'Nebulae', blurb: 'Weather on a galactic scale' },
  { id: 'cluster', label: 'Clusters', blurb: 'Stars that travel together' },
  { id: 'galaxy', label: 'Galaxies', blurb: 'Islands of a hundred billion suns' },
  { id: 'blackhole', label: 'Black holes', blurb: 'Where the map stops' },
  { id: 'exoplanet', label: 'Exoplanets', blurb: 'Other people’s skies' },
  { id: 'probe', label: 'Human artefacts', blurb: 'Things we threw far enough' },
  { id: 'structure', label: 'Cosmic structure', blurb: 'The shape of everything' },
  { id: 'edge', label: 'The edge', blurb: 'As far as looking goes' },
];

export type SkyBody =
  | 'none'
  | 'moon'
  | 'planet'
  | 'sun'
  | 'star'
  | 'binary'
  | 'nebula'
  | 'galaxy'
  | 'blackhole'
  | 'cluster'
  | 'void'
  | 'wall';

export type Horizon = 'none' | 'hills' | 'ridge' | 'trees' | 'shrine' | 'sea' | 'city';

export interface Sky {
  /** Vertical gradient: zenith, middle, horizon. */
  gradient: [string, string, string];
  /** Colour of the glow sitting on the horizon line. */
  glow: string;
  /** Colour of the feature body and of UI accents on this page. */
  accent: string;
  /** Star density multiplier, 0 (empty) to 2 (crowded). */
  stars: number;
  /** Long-exposure star trails instead of points. */
  trails?: boolean;
  /** Amount of nebular haze, 0 to 1. */
  haze: number;
  body: SkyBody;
  /** Relative size of the feature body. */
  bodyScale?: number;
  horizon: Horizon;
}

export type Mood = 'calm' | 'wonder' | 'vast' | 'dark' | 'warm' | 'crystal' | 'ancient';

export interface Destination {
  slug: string;
  /** What goes in the destination field, exactly as the poster would print it. */
  name: string;
  /** Optional qualifier printed under the name. */
  designation?: string;
  category: Category;
  /** Straight-line distance from Earth, in kilometres. */
  distanceKm: number;
  /** How that distance was pinned down — closest approach, mean, comoving… */
  basis: string;
  /** One line, printed under the card. */
  blurb: string;
  /** A longer field note for the journey section. */
  note: string;
  /** A fact worth the trip. */
  fact: string;
  sky: Sky;
  mood: Mood;
}

/** Earth — never a destination, always the origin. */
export const EARTH: Destination = {
  slug: 'earth',
  name: 'Earth',
  category: 'planet',
  distanceKm: 0,
  basis: 'you are here',
  blurb: 'Sea level, one atmosphere, gravity at 9.8 metres per second squared.',
  note: 'The only place anyone has ever left from, and so far the only place anyone has come back to.',
  fact: 'Every human who has ever lived has been within 400,000 km of this spot.',
  mood: 'calm',
  sky: {
    gradient: ['#040a1e', '#0b1e46', '#1d4a86'],
    glow: '#8fbfe8',
    accent: '#cfe4ff',
    stars: 1,
    haze: 0.15,
    body: 'none',
    horizon: 'hills',
  },
};

export const DESTINATIONS: Destination[] = [
  {
    slug: 'moon',
    name: 'Moon',
    category: 'moon',
    distanceKm: 384_400,
    basis: 'mean orbital distance',
    blurb: 'Close enough to walk to, if you had nine hundred lifetimes and a road.',
    note: 'The only other ground twelve people have stood on. Their bootprints are still there, sharp-edged, because there is no wind to soften them and no rain to wash them away.',
    fact: 'It drifts 3.8 cm further away every year. The last total solar eclipse will happen in about 600 million years.',
    mood: 'calm',
    sky: {
      gradient: ['#062159', '#0d55a4', '#67a9de'],
      glow: '#a8d2f2',
      accent: '#eef4ff',
      stars: 0.5,
      haze: 0.1,
      body: 'moon',
      bodyScale: 1,
      horizon: 'hills',
    },
  },
  {
    slug: 'venus',
    name: 'Venus',
    category: 'planet',
    distanceKm: 41_400_000,
    basis: 'closest approach',
    blurb: 'The brightest thing in the sky that is not the Sun or the Moon.',
    note: 'A world the size of ours, wrapped in cloud, held at 464 degrees by an atmosphere that never lets go of the heat. Landers have survived down there for two hours at most.',
    fact: 'A day on Venus is longer than its year, and the Sun rises in the west.',
    mood: 'warm',
    sky: {
      gradient: ['#161638', '#4b3162', '#dfa397'],
      glow: '#f6bda6',
      accent: '#ffe7d4',
      stars: 0.8,
      haze: 0.3,
      body: 'planet',
      bodyScale: 0.5,
      horizon: 'ridge',
    },
  },
  {
    slug: 'mars',
    name: 'Mars',
    category: 'planet',
    distanceKm: 54_600_000,
    basis: 'closest approach',
    blurb: 'The next set of bootprints goes here.',
    note: 'Half our diameter, a third of our gravity, a hundredth of our air. It has the tallest volcano and the deepest canyon in the solar system, and it is quietly rusting.',
    fact: 'Sunsets on Mars are blue. Fine dust scatters red light away and leaves the blue near the Sun.',
    mood: 'warm',
    sky: {
      gradient: ['#1c0a12', '#5b2022', '#c86f47'],
      glow: '#e9a071',
      accent: '#ffcba6',
      stars: 0.9,
      haze: 0.25,
      body: 'planet',
      bodyScale: 0.38,
      horizon: 'ridge',
    },
  },
  {
    slug: 'sun',
    name: 'The Sun',
    category: 'star',
    distanceKm: au(1),
    basis: 'one astronomical unit',
    blurb: 'Eight minutes and twenty seconds away at the only speed that matters.',
    note: 'An unremarkable yellow dwarf, four and a half billion years into a ten billion year life, converting six hundred million tonnes of hydrogen every second so that mornings happen.',
    fact: 'Light made in the core takes tens of thousands of years to fight its way out. Then eight minutes to reach your face.',
    mood: 'warm',
    sky: {
      gradient: ['#2b0d05', '#7d2f0b', '#eb8f3e'],
      glow: '#ffc36b',
      accent: '#ffdca1',
      stars: 0.1,
      haze: 0.45,
      body: 'sun',
      bodyScale: 1.1,
      horizon: 'sea',
    },
  },
  {
    slug: 'jupiter',
    name: 'Jupiter',
    category: 'planet',
    distanceKm: 588_000_000,
    basis: 'closest approach',
    blurb: 'A storm wider than Earth that has been running for centuries.',
    note: 'Two and a half times the mass of every other planet combined, and still not heavy enough to be a star. It has no surface to land on — only pressure, then more pressure.',
    fact: 'Jupiter does not orbit the Sun exactly. They both orbit a point just outside the Sun’s surface.',
    mood: 'vast',
    sky: {
      gradient: ['#0a0a1e', '#2c2141', '#ba8b5e'],
      glow: '#dcb384',
      accent: '#f5dcb8',
      stars: 1,
      haze: 0.3,
      body: 'planet',
      bodyScale: 0.85,
      horizon: 'none',
    },
  },
  {
    slug: 'saturn',
    name: 'Saturn',
    category: 'planet',
    distanceKm: 1_200_000_000,
    basis: 'closest approach',
    blurb: 'Rings of ice the width of a house, in a sheet ten metres thick.',
    note: 'Light enough to float in a big enough ocean. The rings are barely thirty million years old and will be gone in another hundred million — we happen to be here for the good part.',
    fact: 'Its hexagonal polar storm is 30,000 km across and has six flat sides. Nobody is entirely sure why.',
    mood: 'wonder',
    sky: {
      gradient: ['#08091c', '#1f2441', '#caaf7b'],
      glow: '#e2c795',
      accent: '#f7e6c2',
      stars: 1.1,
      haze: 0.25,
      body: 'planet',
      bodyScale: 0.8,
      horizon: 'none',
    },
  },
  {
    slug: 'europa',
    name: 'Europa',
    designation: 'Jupiter II',
    category: 'moon',
    distanceKm: 628_000_000,
    basis: 'via Jupiter, closest approach',
    blurb: 'More liquid water than every ocean on Earth, under twenty kilometres of ice.',
    note: 'Tidal kneading from Jupiter keeps the interior warm. The surface is the youngest in the solar system — smooth, cracked, and constantly resurfaced from below.',
    fact: 'If anything is alive out there, this is the shortest list of places it could be.',
    mood: 'crystal',
    sky: {
      gradient: ['#04101c', '#0c2e4d', '#93d6ea'],
      glow: '#bde9f6',
      accent: '#e6faff',
      stars: 1.1,
      haze: 0.2,
      body: 'planet',
      bodyScale: 0.42,
      horizon: 'ridge',
    },
  },
  {
    slug: 'titan',
    name: 'Titan',
    designation: 'Saturn VI',
    category: 'moon',
    distanceKm: 1_200_000_000,
    basis: 'via Saturn, closest approach',
    blurb: 'Rain, rivers, lakes and seas — all of it methane.',
    note: 'The only moon with a real atmosphere, thick enough that a human could fly there by strapping wings to their arms. It is 179 degrees below zero and it has a weather forecast.',
    fact: 'Huygens landed here in 2005 and sent back the sound of wind. It is the furthest landing ever made.',
    mood: 'ancient',
    sky: {
      gradient: ['#170c04', '#472c11', '#cb8c3d'],
      glow: '#e0ab63',
      accent: '#ffd9a2',
      stars: 0.3,
      haze: 0.6,
      body: 'planet',
      bodyScale: 0.55,
      horizon: 'sea',
    },
  },
  {
    slug: 'enceladus',
    name: 'Enceladus',
    designation: 'Saturn II',
    category: 'moon',
    distanceKm: 1_200_000_000,
    basis: 'via Saturn, closest approach',
    blurb: 'A small white moon that sprays its ocean into space.',
    note: 'Five hundred kilometres wide and almost perfectly reflective. Geysers at the south pole throw salt water hundreds of kilometres up; Cassini flew through the plume and tasted it.',
    fact: 'One of Saturn’s rings is made entirely of Enceladus’ exhaust.',
    mood: 'crystal',
    sky: {
      gradient: ['#040d16', '#0e2c40', '#cfeaf3'],
      glow: '#e8f7fd',
      accent: '#ffffff',
      stars: 1.2,
      haze: 0.15,
      body: 'planet',
      bodyScale: 0.3,
      horizon: 'ridge',
    },
  },
  {
    slug: 'neptune',
    name: 'Neptune',
    category: 'planet',
    distanceKm: 4_300_000_000,
    basis: 'closest approach',
    blurb: 'The last planet, and the windiest place we know of.',
    note: 'Found with mathematics before it was found with a telescope. Winds reach 2,100 km/h out here, powered by almost no sunlight at all, and nobody has a satisfying explanation.',
    fact: 'It has completed one orbit since its discovery. Its year is 165 of ours.',
    mood: 'vast',
    sky: {
      gradient: ['#01081c', '#062a5e', '#3f83d4'],
      glow: '#79b3ee',
      accent: '#cfe6ff',
      stars: 1.2,
      haze: 0.2,
      body: 'planet',
      bodyScale: 0.6,
      horizon: 'none',
    },
  },
  {
    slug: 'pluto',
    name: 'Pluto',
    designation: '134340',
    category: 'planet',
    distanceKm: 5_050_000_000,
    basis: 'mean distance',
    blurb: 'A heart-shaped plain of frozen nitrogen, demoted but unbothered.',
    note: 'For seventy-six years it was a smudge. Then New Horizons went past in 2015 at 50,000 km/h and gave us mountains of water ice, glaciers, and a haze that goes up two hundred kilometres.',
    fact: 'It has not completed a single orbit since humans discovered it. It gets around in 248 years.',
    mood: 'dark',
    sky: {
      gradient: ['#05050d', '#1b1726', '#6d6272'],
      glow: '#9a8fa4',
      accent: '#e2dae8',
      stars: 1.3,
      haze: 0.12,
      body: 'planet',
      bodyScale: 0.35,
      horizon: 'ridge',
    },
  },
  {
    slug: 'voyager-1',
    name: 'Voyager 1',
    category: 'probe',
    distanceKm: 25_100_000_000,
    basis: 'heliocentric range, 2025',
    blurb: 'The furthest thing we have ever made, still transmitting.',
    note: 'Launched in 1977 with less computing power than a modern doorbell. It left the heliosphere in 2012 and is now in interstellar space, running on a plutonium battery that will go quiet in the 2030s.',
    fact: 'It carries a gold record of whale song, greetings in 55 languages, and the sound of a kiss.',
    mood: 'ancient',
    sky: {
      gradient: ['#02030a', '#070e1e', '#0e1c34'],
      glow: '#2f4468',
      accent: '#d4dced',
      stars: 1.6,
      haze: 0.1,
      body: 'star',
      bodyScale: 0.32,
      horizon: 'none',
    },
  },
  {
    slug: 'oort-cloud',
    name: 'Oort Cloud',
    designation: 'outer edge',
    category: 'structure',
    distanceKm: au(100_000),
    basis: 'estimated outer boundary',
    blurb: 'A shell of a trillion frozen comets, and the real edge of the solar system.',
    note: 'Nobody has seen it. We infer it from the long-period comets that fall inward out of nowhere. Out here the Sun is just the brightest star, and the nearest one is a quarter of the way closer than you think.',
    fact: 'Voyager 1 will reach the inner edge in about 300 years and take 30,000 to cross it.',
    mood: 'dark',
    sky: {
      gradient: ['#010209', '#050a18', '#0a1224'],
      glow: '#2a3a58',
      accent: '#b9c6de',
      stars: 1.7,
      haze: 0.08,
      body: 'star',
      bodyScale: 0.12,
      horizon: 'none',
    },
  },
  {
    slug: 'proxima-centauri',
    name: 'Proxima Centauri',
    designation: 'nearest star',
    category: 'star',
    distanceKm: ly(4.2465),
    basis: 'parallax',
    blurb: 'The closest star to the Sun, and far too faint to see.',
    note: 'A red dwarf a seventh our Sun’s width, so dim you need a telescope despite it being our nearest neighbour. It will still be burning long after every star you can see tonight has died.',
    fact: 'It flares violently. In 2019 it brightened 14,000-fold for seven seconds.',
    mood: 'dark',
    sky: {
      gradient: ['#12040a', '#33111c', '#6e2528'],
      glow: '#9c3c36',
      accent: '#ff9b78',
      stars: 1.5,
      haze: 0.18,
      body: 'star',
      bodyScale: 0.7,
      horizon: 'none',
    },
  },
  {
    slug: 'proxima-b',
    name: 'Proxima b',
    category: 'exoplanet',
    distanceKm: ly(4.2465),
    basis: 'parallax to host star',
    blurb: 'An Earth-sized world in the habitable zone of the nearest star.',
    note: 'It orbits every eleven days, tidally locked, one face in permanent day and the other in permanent night. Whether it kept an atmosphere under all that stellar flaring is the whole question.',
    fact: 'This is the nearest exoplanet that will ever exist. There is nothing closer to find.',
    mood: 'dark',
    sky: {
      gradient: ['#100309', '#31101b', '#6d2325'],
      glow: '#a94438',
      accent: '#ff8a63',
      stars: 1.4,
      haze: 0.22,
      body: 'planet',
      bodyScale: 0.55,
      horizon: 'ridge',
    },
  },
  {
    slug: 'sirius',
    name: 'Sirius',
    designation: 'Alpha Canis Majoris',
    category: 'star',
    distanceKm: ly(8.6),
    basis: 'parallax',
    blurb: 'The brightest star in the night sky, and it has a dead companion.',
    note: 'Twenty-five times the Sun’s luminosity, close enough that it dominates winter. Circling it is Sirius B, a white dwarf holding the mass of the Sun inside the volume of Earth.',
    fact: 'The Egyptians timed the Nile flood by its return to the dawn sky.',
    mood: 'crystal',
    sky: {
      gradient: ['#020610', '#08182f', '#123256'],
      glow: '#4d86bf',
      accent: '#dbeaff',
      stars: 1.4,
      haze: 0.14,
      body: 'binary',
      bodyScale: 0.9,
      horizon: 'trees',
    },
  },
  {
    slug: 'vega',
    name: 'Vega',
    designation: 'Alpha Lyrae',
    category: 'star',
    distanceKm: ly(25.04),
    basis: 'parallax',
    blurb: 'The star every other star’s brightness was measured against.',
    note: 'Spinning so fast it is visibly squashed, a day lasting twelve and a half hours. It has a disc of dust around it, which may be the debris of planets we cannot yet see.',
    fact: 'In 12,000 years, precession will make Vega the pole star instead of Polaris.',
    mood: 'crystal',
    sky: {
      gradient: ['#030815', '#0b1e3f', '#1a4270'],
      glow: '#6aa4d8',
      accent: '#e6f0ff',
      stars: 1.3,
      haze: 0.16,
      body: 'star',
      bodyScale: 1,
      horizon: 'trees',
    },
  },
  {
    slug: 'polaris',
    name: 'Polaris',
    designation: 'the North Star',
    category: 'star',
    distanceKm: ly(430.1),
    basis: 'parallax, Hubble 2018',
    blurb: 'The one point the whole northern sky turns around.',
    note: 'Not the brightest star, just the best placed — within a degree of the celestial pole. Leave a camera open for an hour and every other star draws a circle around it.',
    fact: 'It is a triple system, and it pulses: a Cepheid variable brightening and dimming every four days.',
    mood: 'wonder',
    sky: {
      gradient: ['#01030c', '#050c1f', '#0b1832'],
      glow: '#33507e',
      accent: '#e4ecff',
      stars: 1.5,
      trails: true,
      haze: 0.1,
      body: 'none',
      horizon: 'shrine',
    },
  },
  {
    slug: 'betelgeuse',
    name: 'Betelgeuse',
    designation: 'Alpha Orionis',
    category: 'star',
    distanceKm: ly(548),
    basis: 'parallax, uncertain',
    blurb: 'A red supergiant on the edge of going off.',
    note: 'Put it where the Sun is and its surface would swallow Mars. In 2019 it dimmed by two thirds and half the internet decided it was about to explode. It had sneezed out a dust cloud.',
    fact: 'When it does go, it will be visible in daylight for weeks. It may already have happened.',
    mood: 'warm',
    sky: {
      gradient: ['#12040a', '#3d1013', '#8c2a20'],
      glow: '#c9503a',
      accent: '#ffa478',
      stars: 1.2,
      haze: 0.3,
      body: 'star',
      bodyScale: 1.3,
      horizon: 'trees',
    },
  },
  {
    slug: 'rigel',
    name: 'Orion — Rigel',
    designation: 'Beta Orionis',
    category: 'star',
    distanceKm: ly(864.3),
    basis: 'parallax',
    blurb: 'A blue supergiant putting out the light of 120,000 Suns.',
    note: 'The bright foot of Orion. Everything you see of it left in the ninth century — the light arriving tonight started out before the first university existed.',
    fact: 'It is burning through its fuel so fast it will live perhaps eight million years in total.',
    mood: 'crystal',
    sky: {
      gradient: ['#02040f', '#061229', '#0c1f3f'],
      glow: '#2f5c94',
      accent: '#c2d9ff',
      stars: 1.6,
      haze: 0.12,
      body: 'star',
      bodyScale: 1.1,
      horizon: 'trees',
    },
  },
  {
    slug: 'pleiades',
    name: 'Pleiades',
    designation: 'M45 — the Seven Sisters',
    category: 'cluster',
    distanceKm: ly(444),
    basis: 'parallax, Gaia',
    blurb: 'A thousand young stars travelling together through a veil of dust.',
    note: 'The most-recorded object in the sky after the Sun and Moon — in Japanese it is Subaru, in Maori Matariki, and it appears on a bronze disc made in Germany 3,600 years ago.',
    fact: 'Most people see six stars. Your eyes are resolving perhaps a hundredth of what is there.',
    mood: 'wonder',
    sky: {
      gradient: ['#030716', '#0b1738', '#183260'],
      glow: '#4e7fc4',
      accent: '#a9c9ff',
      stars: 1.7,
      haze: 0.4,
      body: 'cluster',
      bodyScale: 1,
      horizon: 'hills',
    },
  },
  {
    slug: 'orion-nebula',
    name: 'Orion Nebula',
    designation: 'M42',
    category: 'nebula',
    distanceKm: ly(1344),
    basis: 'VLBA parallax',
    blurb: 'A stellar nursery you can see with your naked eye.',
    note: 'The middle "star" of Orion’s sword is not a star. It is a cloud twenty-four light years across where a thousand new suns are being switched on, lit from inside by the four hottest of them.',
    fact: 'It is a hollow: a cavity blown out of a much larger dark cloud, and we happen to see in through the side.',
    mood: 'wonder',
    sky: {
      gradient: ['#03040f', '#141a3c', '#33285a'],
      glow: '#7a4a86',
      accent: '#ff96ae',
      stars: 1.5,
      haze: 0.85,
      body: 'nebula',
      bodyScale: 1.2,
      horizon: 'trees',
    },
  },
  {
    slug: 'pillars-of-creation',
    name: 'Pillars of Creation',
    designation: 'M16 — Eagle Nebula',
    category: 'nebula',
    distanceKm: ly(7000),
    basis: 'distance to M16',
    blurb: 'Four light-year columns of gas, actively collapsing into stars.',
    note: 'The most famous photograph ever taken of anything outside the solar system. The towers are being eaten away from outside by the radiation of the stars they are making.',
    fact: 'They may have been destroyed by a supernova 6,000 years ago. The news has not reached us.',
    mood: 'ancient',
    sky: {
      gradient: ['#060310', '#20132c', '#4a2a3c'],
      glow: '#8c4a52',
      accent: '#ffbe8a',
      stars: 1.3,
      haze: 0.9,
      body: 'nebula',
      bodyScale: 1.3,
      horizon: 'none',
    },
  },
  {
    slug: 'crab-nebula',
    name: 'Crab Nebula',
    designation: 'M1',
    category: 'nebula',
    distanceKm: ly(6523),
    basis: 'expansion parallax',
    blurb: 'The wreckage of a star that Chinese astronomers watched explode in 1054.',
    note: 'For twenty-three days it was bright enough to read by at night. What is left is a shell of debris expanding at 1,500 km/s with a neutron star at the centre spinning thirty times a second.',
    fact: 'That pulsar is 20 km across and weighs more than the Sun. A teaspoon of it would weigh a billion tonnes.',
    mood: 'dark',
    sky: {
      gradient: ['#06030c', '#1f0a21', '#3f1332'],
      glow: '#7d2a55',
      accent: '#84ecd9',
      stars: 1.4,
      haze: 0.75,
      body: 'nebula',
      bodyScale: 1,
      horizon: 'none',
    },
  },
  {
    slug: 'helix-nebula',
    name: 'Helix Nebula',
    designation: 'NGC 7293',
    category: 'nebula',
    distanceKm: ly(655),
    basis: 'Gaia parallax',
    blurb: 'A sun-like star breathing out, seen end-on.',
    note: 'Nicknamed the Eye of God, which undersells it. This is the ordinary death of an ordinary star — the outer layers drifting off, the naked core left glowing in the middle.',
    fact: 'In about five billion years the Sun will make one of these, and we will be inside it.',
    mood: 'crystal',
    sky: {
      gradient: ['#030711', '#0b2240', '#134055'],
      glow: '#2c7d84',
      accent: '#6ee6cd',
      stars: 1.3,
      haze: 0.7,
      body: 'nebula',
      bodyScale: 0.9,
      horizon: 'none',
    },
  },
  {
    slug: 'carina-nebula',
    name: 'Carina Nebula',
    designation: 'NGC 3372',
    category: 'nebula',
    distanceKm: ly(8500),
    basis: 'cluster fitting',
    blurb: 'Cosmic cliffs, seven light years tall.',
    note: 'Four times the size of Orion and far brighter, but too far south for most of the world to see. Inside it sits Eta Carinae, a star so unstable it briefly became the second brightest in the sky in 1843.',
    fact: 'The first image JWST ever released to the public was a corner of this cloud.',
    mood: 'wonder',
    sky: {
      gradient: ['#050310', '#1d1032', '#4a2148'],
      glow: '#8a3f6e',
      accent: '#ffb0d0',
      stars: 1.5,
      haze: 0.95,
      body: 'nebula',
      bodyScale: 1.4,
      horizon: 'none',
    },
  },
  {
    slug: 'trappist-1e',
    name: 'TRAPPIST-1e',
    category: 'exoplanet',
    distanceKm: ly(40.7),
    basis: 'parallax to host star',
    blurb: 'One of seven rocky worlds circling a very small, very cool star.',
    note: 'All seven orbit closer than Mercury does to the Sun. Standing on 1e, the neighbouring planets would appear larger in the sky than our Moon does, showing phases.',
    fact: 'Its year is six days long, and its sky is permanently the colour of a dying ember.',
    mood: 'dark',
    sky: {
      gradient: ['#0d0512', '#2b1131', '#5e2242'],
      glow: '#9b3a63',
      accent: '#ff9ad5',
      stars: 1.3,
      haze: 0.3,
      body: 'planet',
      bodyScale: 0.6,
      horizon: 'ridge',
    },
  },
  {
    slug: 'k2-18b',
    name: 'K2-18b',
    category: 'exoplanet',
    distanceKm: ly(124),
    basis: 'Gaia parallax',
    blurb: 'A world eight times our mass, with water vapour in the air.',
    note: 'Possibly a hycean planet: a deep global ocean under a hydrogen atmosphere. JWST has caught hints of molecules there that, on Earth, are only made by living things.',
    fact: 'Hints are not evidence. But this is the most interesting maybe in astronomy right now.',
    mood: 'calm',
    sky: {
      gradient: ['#04101a', '#0d2c3f', '#1e5a63'],
      glow: '#3d9c94',
      accent: '#8ef0e0',
      stars: 1.2,
      haze: 0.35,
      body: 'planet',
      bodyScale: 0.7,
      horizon: 'sea',
    },
  },
  {
    slug: 'cygnus-x-1',
    name: 'Cygnus X-1',
    category: 'blackhole',
    distanceKm: ly(7200),
    basis: 'VLBA parallax, 2021',
    blurb: 'The first black hole anyone believed in.',
    note: 'Twenty-one solar masses pulling gas off a blue supergiant companion. The infalling material spirals in, heats to millions of degrees and screams in X-rays before it disappears.',
    fact: 'Stephen Hawking bet Kip Thorne it was not a black hole. He conceded in 1990 and paid up in magazine subscriptions.',
    mood: 'dark',
    sky: {
      gradient: ['#050208', '#160719', '#2f0f2a'],
      glow: '#6a2244',
      accent: '#8fb8ff',
      stars: 1.3,
      haze: 0.5,
      body: 'blackhole',
      bodyScale: 0.75,
      horizon: 'none',
    },
  },
  {
    slug: 'sagittarius-a-star',
    name: 'Sagittarius A*',
    designation: 'galactic centre',
    category: 'blackhole',
    distanceKm: ly(26_000),
    basis: 'GRAVITY interferometry',
    blurb: 'Four million suns folded into a point, and everything here orbits it.',
    note: 'The Sun takes 230 million years to go around it once. We have watched individual stars whip past at 24 million km/h and swing back, which is how we know exactly how heavy it is.',
    fact: 'It was photographed in 2022. The shadow is 52 microarcseconds across — a doughnut on the Moon.',
    mood: 'vast',
    sky: {
      gradient: ['#04030a', '#160a1e', '#3d1531'],
      glow: '#8a3f2e',
      accent: '#ffb066',
      stars: 2,
      haze: 0.8,
      body: 'blackhole',
      bodyScale: 1.1,
      horizon: 'none',
    },
  },
  {
    slug: 'm87-star',
    name: 'M87*',
    designation: 'Virgo A',
    category: 'blackhole',
    distanceKm: ly(53_490_000),
    basis: 'surface brightness fluctuation',
    blurb: 'The first black hole ever photographed. Six and a half billion suns.',
    note: 'The event horizon is larger than the orbit of Neptune. It fires a jet of plasma five thousand light years out of its host galaxy, and that jet has been visible in telescopes since 1918.',
    fact: 'The 2019 image was assembled from eight telescopes and half a tonne of hard drives flown by plane.',
    mood: 'vast',
    sky: {
      gradient: ['#050208', '#180719', '#3a0f22'],
      glow: '#8d3418',
      accent: '#ffbe52',
      stars: 1.1,
      haze: 0.6,
      body: 'blackhole',
      bodyScale: 1.3,
      horizon: 'none',
    },
  },
  {
    slug: 'ton-618',
    name: 'TON 618',
    category: 'blackhole',
    distanceKm: ly(10_370_000_000),
    basis: 'comoving distance, z = 2.219',
    blurb: 'Sixty-six billion solar masses. Among the heaviest things known.',
    note: 'A quasar: a black hole feeding so hard that its accretion disc outshines every star in its galaxy combined, by a factor of a hundred. We see it as it was when the universe was three billion years old.',
    fact: 'Its event horizon is 1,300 astronomical units across. Light takes weeks to cross it.',
    mood: 'vast',
    sky: {
      gradient: ['#050109', '#170419', '#2f0824'],
      glow: '#7a2140',
      accent: '#ffd08a',
      stars: 0.8,
      haze: 0.7,
      body: 'blackhole',
      bodyScale: 1.5,
      horizon: 'none',
    },
  },
  {
    slug: 'omega-centauri',
    name: 'Omega Centauri',
    designation: 'NGC 5139',
    category: 'cluster',
    distanceKm: ly(17_090),
    basis: 'globular cluster fitting',
    blurb: 'Ten million ancient stars packed into a ball 150 light years wide.',
    note: 'The largest globular cluster orbiting our galaxy, and probably not a cluster at all — most likely the stripped core of a dwarf galaxy the Milky Way ate a long time ago.',
    fact: 'At its centre, stars are half a light year apart. Night there would never really be dark.',
    mood: 'ancient',
    sky: {
      gradient: ['#050408', '#181328', '#382b4a'],
      glow: '#6b5580',
      accent: '#ffe9c2',
      stars: 2,
      haze: 0.45,
      body: 'cluster',
      bodyScale: 1.2,
      horizon: 'hills',
    },
  },
  {
    slug: 'large-magellanic-cloud',
    name: 'Large Magellanic Cloud',
    category: 'galaxy',
    distanceKm: ly(163_000),
    basis: 'eclipsing binary distance',
    blurb: 'A satellite galaxy, and a smudge you can see from a dark southern sky.',
    note: 'Twenty billion stars falling slowly toward the Milky Way. It contains the Tarantula Nebula, the single most violent star-forming region in the Local Group.',
    fact: 'SN 1987A went off here. It is the only supernova in four centuries close enough to study properly.',
    mood: 'wonder',
    sky: {
      gradient: ['#03040e', '#0d1028', '#242a52'],
      glow: '#4a4d8a',
      accent: '#cfd6ff',
      stars: 1.8,
      haze: 0.55,
      body: 'galaxy',
      bodyScale: 1,
      horizon: 'hills',
    },
  },
  {
    slug: 'andromeda',
    name: 'Andromeda',
    designation: 'M31',
    category: 'galaxy',
    distanceKm: ly(2_537_000),
    basis: 'Cepheid variables',
    blurb: 'The furthest thing visible to the unaided eye, and it is coming for us.',
    note: 'A trillion stars, six times wider than the full Moon in the sky if your eyes were sensitive enough. It is closing at 110 km/s and will merge with the Milky Way in about four billion years.',
    fact: 'You can see it tonight without a telescope. The photons hitting your retina left before our species existed.',
    mood: 'vast',
    sky: {
      gradient: ['#02030c', '#0a0a26', '#2c2b60'],
      glow: '#514c94',
      accent: '#cdb8ff',
      stars: 1.6,
      haze: 0.5,
      body: 'galaxy',
      bodyScale: 1.25,
      horizon: 'hills',
    },
  },
  {
    slug: 'whirlpool',
    name: 'Whirlpool Galaxy',
    designation: 'M51a',
    category: 'galaxy',
    distanceKm: ly(31_000_000),
    basis: 'planetary nebula luminosity',
    blurb: 'The first object ever recognised as a spiral, in 1845.',
    note: 'Two galaxies mid-collision, seen face on. The small one has been passing through the big one for hundreds of millions of years and its gravity is what makes the arms so absurdly photogenic.',
    fact: 'Lord Rosse sketched its spiral by eye through a 72-inch telescope, and nobody believed him.',
    mood: 'wonder',
    sky: {
      gradient: ['#03040e', '#101031', '#2c2160'],
      glow: '#5b3f96',
      accent: '#b6c8ff',
      stars: 1.4,
      haze: 0.55,
      body: 'galaxy',
      bodyScale: 1.15,
      horizon: 'none',
    },
  },
  {
    slug: 'gn-z11',
    name: 'GN-z11',
    category: 'galaxy',
    distanceKm: ly(32_000_000_000),
    basis: 'comoving distance, z = 10.6',
    blurb: 'A galaxy from when the universe was 400 million years old.',
    note: 'One of the oldest things ever identified. It is a twenty-fifth the size of the Milky Way and forming stars twenty times faster, in a universe that had barely finished being opaque.',
    fact: 'The light took 13.4 billion years to arrive. Expansion has since carried the galaxy far further away.',
    mood: 'ancient',
    sky: {
      gradient: ['#06010a', '#1c0620', '#43103a'],
      glow: '#8a2d52',
      accent: '#ffc9a0',
      stars: 0.9,
      haze: 0.6,
      body: 'galaxy',
      bodyScale: 0.55,
      horizon: 'none',
    },
  },
  {
    slug: 'bootes-void',
    name: 'Boötes Void',
    designation: 'the Great Nothing',
    category: 'structure',
    distanceKm: ly(700_000_000),
    basis: 'redshift survey',
    blurb: 'A sphere 330 million light years across with almost nothing in it.',
    note: 'It should hold about two thousand galaxies. It holds sixty. If the Milky Way sat at its centre, we would not have known other galaxies existed until the 1960s.',
    fact: 'It is the emptiest known region of the observable universe, and nobody is sure how it got that way.',
    mood: 'dark',
    sky: {
      gradient: ['#010104', '#04040a', '#08080f'],
      glow: '#151726',
      accent: '#5b6480',
      stars: 0.15,
      haze: 0.05,
      body: 'void',
      bodyScale: 1,
      horizon: 'none',
    },
  },
  {
    slug: 'laniakea',
    name: 'Laniakea',
    designation: 'supercluster boundary',
    category: 'structure',
    distanceKm: ly(260_000_000),
    basis: 'to the far edge of the supercluster',
    blurb: 'The supercluster we live in. Its name means immeasurable heaven.',
    note: 'A hundred thousand galaxies, five hundred million light years across, all of them flowing toward a common gravitational focus. It was only defined and named in 2014.',
    fact: 'Dark energy is pulling it apart. Laniakea is not gravitationally bound and will not survive.',
    mood: 'vast',
    sky: {
      gradient: ['#020208', '#0b0919', '#171233'],
      glow: '#332c66',
      accent: '#aeb8ff',
      stars: 1.2,
      haze: 0.7,
      body: 'wall',
      bodyScale: 1,
      horizon: 'none',
    },
  },
  {
    slug: 'great-attractor',
    name: 'The Great Attractor',
    category: 'structure',
    distanceKm: ly(250_000_000),
    basis: 'peculiar velocity field',
    blurb: 'Something is pulling our entire galaxy at two million kilometres an hour.',
    note: 'It sits behind the plane of the Milky Way, in the Zone of Avoidance, where our own galaxy’s dust blocks the view. We can measure its pull perfectly and barely see it at all.',
    fact: 'We will never arrive. Cosmic expansion is winning, and it is receding faster than we fall.',
    mood: 'dark',
    sky: {
      gradient: ['#030209', '#0d0718', '#1f0e2e'],
      glow: '#3d1e52',
      accent: '#c9a6ff',
      stars: 1,
      haze: 0.75,
      body: 'wall',
      bodyScale: 1.2,
      horizon: 'none',
    },
  },
  {
    slug: 'hercules-corona-borealis',
    name: 'Hercules–Corona Borealis Great Wall',
    category: 'structure',
    distanceKm: ly(10_000_000_000),
    basis: 'gamma-ray burst clustering',
    blurb: 'The largest structure ever found. Ten billion light years long.',
    note: 'A filament of galaxy superclusters so big it may violate the cosmological principle — the assumption that on large enough scales, the universe looks the same everywhere.',
    fact: 'Crossing it at the speed of light takes longer than the universe has existed.',
    mood: 'ancient',
    sky: {
      gradient: ['#040108', '#150520', '#31103c'],
      glow: '#5f2166',
      accent: '#d7b4ff',
      stars: 0.7,
      haze: 0.8,
      body: 'wall',
      bodyScale: 1.4,
      horizon: 'none',
    },
  },
  {
    slug: 'cosmic-microwave-background',
    name: 'The Last Scattering',
    designation: 'cosmic microwave background',
    category: 'edge',
    distanceKm: ly(45_700_000_000),
    basis: 'comoving distance, z = 1100',
    blurb: 'The oldest light there is. The moment the universe turned transparent.',
    note: 'For 380,000 years after the Big Bang the universe was an opaque fog. Then it cooled enough for atoms to hold together, and the light that was released has been travelling ever since.',
    fact: 'A small fraction of old analogue TV static was this. You have already seen the beginning of everything.',
    mood: 'ancient',
    sky: {
      gradient: ['#050107', '#1c0722', '#45123e'],
      glow: '#93341f',
      accent: '#ffd9a0',
      stars: 0.4,
      haze: 1,
      body: 'wall',
      bodyScale: 1.6,
      horizon: 'none',
    },
  },
  {
    slug: 'observable-edge',
    name: 'The Observable Edge',
    designation: 'particle horizon',
    category: 'edge',
    distanceKm: ly(46_500_000_000),
    basis: 'comoving radius of the observable universe',
    blurb: 'The furthest anything can be and still be, in principle, seen.',
    note: 'Not an edge of the universe — an edge of what has had time to reach us. It grows every second, and yet because of expansion, most of what lies beyond it is already permanently out of reach.',
    fact: 'The universe is 13.8 billion years old, but this horizon is 46.5 billion light years away. Space stretched on the way.',
    mood: 'vast',
    sky: {
      gradient: ['#020105', '#0c0316', '#1e0a2c'],
      glow: '#3b1250',
      accent: '#e0c4ff',
      stars: 0.5,
      haze: 0.9,
      body: 'void',
      bodyScale: 1,
      horizon: 'none',
    },
  },
];

/** Every catalog entry keyed by slug, Earth included. */
export const BY_SLUG: Record<string, Destination> = Object.fromEntries(
  [EARTH, ...DESTINATIONS].map((d) => [d.slug, d]),
);

export const getDestination = (slug: string): Destination | undefined => BY_SLUG[slug];

export const destinationsIn = (category: Category): Destination[] =>
  DESTINATIONS.filter((d) => d.category === category);

/** Catalog order is roughly by distance; this makes that explicit. */
export const BY_DISTANCE: Destination[] = [...DESTINATIONS].sort((a, b) => a.distanceKm - b.distanceKm);

export function neighbours(slug: string): { previous: Destination; next: Destination } {
  const index = Math.max(0, BY_DISTANCE.findIndex((d) => d.slug === slug));
  const size = BY_DISTANCE.length;
  return {
    previous: BY_DISTANCE[(index - 1 + size) % size],
    next: BY_DISTANCE[(index + 1) % size],
  };
}

/**
 * Distance between two catalog entries.
 *
 * Everything is catalogued as a radial distance from Earth, so this is a
 * first-order separation, exact when the origin is Earth and honest-ish
 * otherwise. The site says as much wherever a non-Earth origin is picked.
 */
export function separation(origin: Destination, destination: Destination): number {
  return Math.abs(destination.distanceKm - origin.distanceKm);
}

/** Origins worth offering. Anything further out stops being a journey. */
export const ORIGIN_SLUGS = ['earth', 'moon', 'mars', 'voyager-1', 'oort-cloud'];

export const ORIGINS: Destination[] = ORIGIN_SLUGS.map((slug) => BY_SLUG[slug]).filter(Boolean);
